"""empty message

Revision ID: 14598d70ecca
Revises: 855530dae19e
Create Date: 2023-06-01 14:57:36.278971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14598d70ecca'
down_revision = '855530dae19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('selling')

    # ### end Alembic commands ###
