"""empty message

Revision ID: 62f8cbef1c92
Revises: f4e807a8157e
Create Date: 2023-07-04 14:45:58.307185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f8cbef1c92'
down_revision = 'f4e807a8157e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rated', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
