"""empty message

Revision ID: 855530dae19e
Revises: d356e8227e13
Create Date: 2023-05-30 11:34:21.080150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855530dae19e'
down_revision = 'd356e8227e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    with op.batch_alter_table('rated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rated', schema=None) as batch_op:
        batch_op.drop_column('review')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
