"""empty message

Revision ID: f4e807a8157e
Revises: 2f4689a37a87
Create Date: 2023-06-01 15:47:31.349670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e807a8157e'
down_revision = '2f4689a37a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_searched', sa.String(length=60), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('last_searched')

    # ### end Alembic commands ###
